let targetsSearchTimer=null;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function dt(v){if(!v)return '—';const d=new Date(v.endsWith?.('Z')?v:`${v}Z`);return Number.isNaN(d.getTime())?v:d.toLocaleString('pt-BR')}
async function json(r){const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.message||`Erro HTTP ${r.status}`);return d}
function showTab(tab){const scans=tab==='scans';document.getElementById('machinesSection').hidden=scans;document.getElementById('scansSection').hidden=!scans;document.getElementById('navMachines').classList.toggle('active',!scans);document.getElementById('navScans').classList.toggle('active',scans);if(scans){loadScans();loadRuns()}else loadTargets()}
async function loadTargets(){const t=document.getElementById('targetsTable'),s=document.getElementById('targetsSearch').value.trim();t.innerHTML='<tr><td colspan="5">Carregando...</td></tr>';try{const d=await json(await fetch(`/api/targets?search=${encodeURIComponent(s)}&limit=500`));targetsTotal.textContent=d.total??0;t.innerHTML=(d.items||[]).length?d.items.map(x=>`<tr><td>${esc(x.hostname||'Nome não identificado')}</td><td><code>${esc(x.ip_address)}</code></td><td><code>${esc(x.mac_address||'Não disponível')}</code></td><td>${esc(dt(x.last_seen_at))}</td><td><button class="btn secondary btn-sm" onclick="deleteTarget('${esc(x.target_uuid)}','${esc(x.ip_address)}')">Excluir</button></td></tr>`).join(''):'<tr><td colspan="5">Nenhum alvo confirmado.</td></tr>';await loadLast()}catch(e){t.innerHTML=`<tr><td colspan="5">${esc(e.message)}</td></tr>`}}
async function loadLast(){try{const d=await json(await fetch('/api/targets/discovery-runs/list?limit=1')),r=d.items?.[0];lastDiscoveryStatus.textContent=r?`${r.status} · ${dt(r.started_at)}`:'Ainda não executada'}catch{lastDiscoveryStatus.textContent='Indisponível'}}
async function deleteTarget(id,ip){if(!confirm(`Excluir o alvo ${ip}? Ele será reativado caso responda a um scan futuro.`))return;await json(await fetch(`/api/targets/${id}`,{method:'DELETE'}));loadTargets()}
function scheduleText(x){return x.schedule_type==='interval'?`A cada ${x.interval_minutes} min`:'Manual'}
async function loadScans(){const t=scansTable;t.innerHTML='<tr><td colspan="7">Carregando...</td></tr>';try{const d=await json(await fetch('/api/targets/scans'));t.innerHTML=(d.items||[]).length?d.items.map(x=>`<tr><td>${esc(x.name)}</td><td><code>${esc(x.target_spec)}</code></td><td>${esc(scheduleText(x))}</td><td>${esc(dt(x.last_run_at))}</td><td>${esc(dt(x.next_run_at))}</td><td>${x.is_running?'Executando':x.is_enabled?'Ativo':x.schedule_type==='manual'?'Manual':'Pausado'}</td><td><button class="btn primary btn-sm" onclick="runScan('${x.scan_uuid}')">Executar</button> <button class="btn secondary btn-sm" onclick="toggleScan('${x.scan_uuid}',${!x.is_enabled})">${x.is_enabled?'Pausar':'Ativar'}</button> <button class="btn secondary btn-sm" onclick="deleteScan('${x.scan_uuid}','${esc(x.name)}')">Excluir</button></td></tr>`).join(''):'<tr><td colspan="7">Nenhum scan configurado.</td></tr>'}catch(e){t.innerHTML=`<tr><td colspan="7">${esc(e.message)}</td></tr>`}}
async function loadRuns(){try{const d=await json(await fetch('/api/targets/discovery-runs/list?limit=100'));runsTable.innerHTML=(d.items||[]).length?d.items.map(x=>{let dur='—';if(x.finished_at){dur=`${Math.max(0,Math.round((new Date(x.finished_at)-new Date(x.started_at))/1000))}s`}return `<tr><td>${esc(x.scan_name||x.target_spec)}</td><td>${esc(dt(x.started_at))}</td><td>${dur}</td><td>${esc(x.trigger_type)}</td><td>${x.addresses_checked??0}</td><td>${x.discovered_count??0}</td><td>${esc(x.status)}${x.runner_id?` · ${esc(x.runner_id)}`:''}${x.error?` — ${esc(x.error)}`:''}</td></tr>`}).join(''):'<tr><td colspan="7">Sem histórico.</td></tr>'}catch(e){runsTable.innerHTML=`<tr><td colspan="7">${esc(e.message)}</td></tr>`}}
async function runScan(id){scanResult.textContent='Enviando scan ao Runner...';try{const d=await json(await fetch(`/api/targets/scans/${id}/run`,{method:'POST'}));scanResult.textContent=d.queued?`Scan enviado ao Runner ${d.runner_id}. Acompanhe o histórico.`:`Concluído: ${d.discovered_count} host(s) confirmado(s).`;await Promise.all([loadScans(),loadRuns(),loadTargets()])}catch(e){scanResult.textContent=`Falha: ${e.message}`;loadRuns()}}
async function toggleScan(id,on){await json(await fetch(`/api/targets/scans/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_enabled:on})}));loadScans()}
async function deleteScan(id,name){const remove=confirm(`Excluir o scan "${name}"?\n\nOK: excluir também máquinas descobertas exclusivamente por ele.\nCancelar: manter máquinas e escolher novamente.`);if(!remove&&!confirm('Excluir somente a configuração e manter as máquinas?'))return;await json(await fetch(`/api/targets/scans/${id}?remove_exclusive_targets=${remove}`,{method:'DELETE'}));Promise.all([loadScans(),loadTargets(),loadRuns()])}
async function saveScan(){const payload={name:scanName.value.trim(),target_spec:scanTarget.value.trim(),schedule_type:scanSchedule.value,interval_minutes:Number(scanInterval.value),is_enabled:scanEnabled.checked,run_now:scanRunNow.checked};scanResult.textContent='Salvando...';try{const d=await json(await fetch('/api/targets/scans',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}));scanResult.textContent=d.run?(d.run.queued?`Scan salvo e enviado ao Runner ${d.run.runner_id}.`:`Salvo e executado: ${d.run.discovered_count} host(s) confirmado(s).`):'Scan salvo.';scanFormCard.hidden=true;await Promise.all([loadScans(),loadRuns(),loadTargets()])}catch(e){scanResult.textContent=`Falha: ${e.message}`}}
document.addEventListener('DOMContentLoaded',()=>{buildHeader('targets');navMachines.onclick=e=>{e.preventDefault();location.hash='machines';showTab('machines')};navScans.onclick=e=>{e.preventDefault();location.hash='scans';showTab('scans')};targetsRefreshBtn.onclick=()=>Promise.all([loadTargets(),loadLast()]);targetsSearch.oninput=()=>{clearTimeout(targetsSearchTimer);targetsSearchTimer=setTimeout(loadTargets,300)};newScanBtn.onclick=()=>scanFormCard.hidden=false;cancelScanBtn.onclick=()=>scanFormCard.hidden=true;scanSchedule.onchange=()=>{intervalLabel.hidden=scanSchedule.value!=='interval';scanEnabled.disabled=scanSchedule.value!=='interval'};saveScanBtn.onclick=saveScan;clearHistoryBtn.onclick=async()=>{if(confirm('Limpar todo o histórico de execuções?')){await json(await fetch('/api/targets/discovery-runs',{method:'DELETE'}));loadRuns()}};showTab(location.hash==='#scans'?'scans':'machines')});
