let assets = [];
let assetSort = { key: 'last_seen_at', direction: 'desc' };
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function dt(v){if(!v)return '—';const raw=String(v);const d=new Date(raw.endsWith('Z')?raw:`${raw}Z`);return Number.isNaN(d.getTime())?raw:d.toLocaleString('pt-BR')}
async function json(r){const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.message||`Erro HTTP ${r.status}`);return d}
function showTab(tab){const scans=tab==='scans';document.getElementById('machinesSection').hidden=scans;document.getElementById('scansSection').hidden=!scans;document.getElementById('navMachines').classList.toggle('active',!scans);document.getElementById('navScans').classList.toggle('active',scans);if(scans){loadScans();loadRuns()}else loadTargets()}
function assetName(x){return x.display_name||x.hostname||x.dns_name||x.ip_address||'Ativo sem nome'}
function sourceLabel(v){const s=String(v||'nmap').toLowerCase();if(s.includes('runner'))return 'Nmap / Runner';if(s.includes('local'))return 'Nmap / Local';if(s==='nmap')return 'Nmap';return v||'Nmap'}
function compareAssets(a,b,key){let av=a[key],bv=b[key];if(key==='display_name'){av=assetName(a);bv=assetName(b)}if(key==='status'){av='detected';bv='detected'}if(key.endsWith('_at')){av=av?new Date(av).getTime():0;bv=bv?new Date(bv).getTime():0;return av-bv}return String(av??'').localeCompare(String(bv??''),'pt-BR',{numeric:true,sensitivity:'base'})}
function filteredAssets(){const q=targetsSearch.value.trim().toLowerCase();const rows=q?assets.filter(x=>[assetName(x),x.hostname,x.dns_name,x.ip_address,x.mac_address,x.vendor,x.runner_name,x.runner_id,x.discovery_source].some(v=>String(v||'').toLowerCase().includes(q))):[...assets];rows.sort((a,b)=>compareAssets(a,b,assetSort.key)*(assetSort.direction==='asc'?1:-1));return rows}
function renderAssets(){const rows=filteredAssets();targetsTable.innerHTML=rows.length?rows.map(x=>{const name=assetName(x);const detail=x.dns_name&&x.dns_name!==name?x.dns_name:(x.hostname&&x.hostname!==name?x.hostname:'');return `<tr><td><span class="asset-status detected">Detectado</span></td><td><span class="asset-name">${esc(name)}${detail?`<small>${esc(detail)}</small>`:''}</span></td><td><code>${esc(x.ip_address)}</code></td><td><code>${esc(x.mac_address||'—')}</code></td><td><span class="asset-badge">${esc(x.vendor||'Desconhecido')}</span></td><td><span class="asset-badge source">${esc(sourceLabel(x.discovery_source))}</span></td><td>${esc(x.runner_name||x.runner_id||'—')}</td><td>${esc(dt(x.first_seen_at))}</td><td>${esc(dt(x.last_seen_at))}</td><td><button class="btn secondary btn-sm" onclick="deleteTarget('${esc(x.target_uuid)}','${esc(x.ip_address)}')">Excluir</button></td></tr>`}).join(''):'<tr><td colspan="10">Nenhum ativo confirmado.</td></tr>';document.querySelectorAll('#machinesSection th[data-sort]').forEach(th=>{th.classList.toggle('sort-asc',th.dataset.sort===assetSort.key&&assetSort.direction==='asc');th.classList.toggle('sort-desc',th.dataset.sort===assetSort.key&&assetSort.direction==='desc')})}
async function loadTargets(){targetsTable.innerHTML='<tr><td colspan="10">Carregando...</td></tr>';try{const d=await json(await fetch('/api/targets?limit=500'));assets=d.items||[];targetsTotal.textContent=d.total??assets.length;renderAssets();await loadLast()}catch(e){targetsTable.innerHTML=`<tr><td colspan="10">${esc(e.message)}</td></tr>`}}
async function loadLast(){try{const d=await json(await fetch('/api/targets/discovery-runs/list?limit=1')),r=d.items?.[0];lastDiscoveryStatus.textContent=r?`${r.status} · ${dt(r.started_at)}`:'Ainda não executada'}catch{lastDiscoveryStatus.textContent='Indisponível'}}
async function deleteTarget(id,ip){if(!confirm(`Excluir o ativo ${ip}? Ele será reativado caso responda a um scan futuro.`))return;await json(await fetch(`/api/targets/${id}`,{method:'DELETE'}));loadTargets()}
function scheduleText(x){return x.schedule_type==='interval'?`A cada ${x.interval_minutes} min`:'Manual'}
async function loadScans(){const t=scansTable;t.innerHTML='<tr><td colspan="7">Carregando...</td></tr>';try{const d=await json(await fetch('/api/targets/scans'));t.innerHTML=(d.items||[]).length?d.items.map(x=>`<tr><td>${esc(x.name)}</td><td><code>${esc(x.target_spec)}</code></td><td>${esc(scheduleText(x))}</td><td>${esc(dt(x.last_run_at))}</td><td>${esc(dt(x.next_run_at))}</td><td>${x.is_running?'Executando':x.is_enabled?'Ativo':x.schedule_type==='manual'?'Manual':'Pausado'}</td><td><button class="btn primary btn-sm" onclick="runScan('${x.scan_uuid}')">Executar</button> <button class="btn secondary btn-sm" onclick="toggleScan('${x.scan_uuid}',${!x.is_enabled})">${x.is_enabled?'Pausar':'Ativar'}</button> <button class="btn secondary btn-sm" onclick="deleteScan('${x.scan_uuid}','${esc(x.name)}')">Excluir</button></td></tr>`).join(''):'<tr><td colspan="7">Nenhum scan configurado.</td></tr>'}catch(e){t.innerHTML=`<tr><td colspan="7">${esc(e.message)}</td></tr>`}}
async function loadRuns(){try{const d=await json(await fetch('/api/targets/discovery-runs/list?limit=100'));runsTable.innerHTML=(d.items||[]).length?d.items.map(x=>{let dur='—';if(x.finished_at){dur=`${Math.max(0,Math.round((new Date(x.finished_at)-new Date(x.started_at))/1000))}s`}return `<tr><td>${esc(x.scan_name||x.target_spec)}</td><td>${esc(dt(x.started_at))}</td><td>${dur}</td><td>${esc(x.trigger_type)}</td><td>${x.addresses_checked??0}</td><td>${x.discovered_count??0}</td><td>${esc(x.status)}${x.runner_id?` · ${esc(x.runner_id)}`:''}${x.error?` — ${esc(x.error)}`:''}</td></tr>`}).join(''):'<tr><td colspan="7">Sem histórico.</td></tr>'}catch(e){runsTable.innerHTML=`<tr><td colspan="7">${esc(e.message)}</td></tr>`}}
async function runScan(id){scanResult.textContent='Enviando scan ao Runner...';try{const d=await json(await fetch(`/api/targets/scans/${id}/run`,{method:'POST'}));scanResult.textContent=d.queued?`Scan enviado ao Runner ${d.runner_id}. Acompanhe o histórico.`:`Concluído: ${d.discovered_count} ativo(s) confirmado(s).`;await Promise.all([loadScans(),loadRuns(),loadTargets()])}catch(e){scanResult.textContent=`Falha: ${e.message}`;loadRuns()}}
async function toggleScan(id,on){await json(await fetch(`/api/targets/scans/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_enabled:on})}));loadScans()}
async function deleteScan(id,name){const remove=confirm(`Excluir o scan "${name}"?\n\nOK: excluir também ativos descobertos exclusivamente por ele.\nCancelar: manter ativos e escolher novamente.`);if(!remove&&!confirm('Excluir somente a configuração e manter os ativos?'))return;await json(await fetch(`/api/targets/scans/${id}?remove_exclusive_targets=${remove}`,{method:'DELETE'}));Promise.all([loadScans(),loadTargets(),loadRuns()])}
async function saveScan(){const payload={name:scanName.value.trim(),target_spec:scanTarget.value.trim(),schedule_type:scanSchedule.value,interval_minutes:Number(scanInterval.value),is_enabled:scanEnabled.checked,run_now:scanRunNow.checked};scanResult.textContent='Salvando...';try{const d=await json(await fetch('/api/targets/scans',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}));scanResult.textContent=d.run?(d.run.queued?`Scan salvo e enviado ao Runner ${d.run.runner_id}.`:`Salvo e executado: ${d.run.discovered_count} ativo(s) confirmado(s).`):'Scan salvo.';scanFormCard.hidden=true;await Promise.all([loadScans(),loadRuns(),loadTargets()])}catch(e){scanResult.textContent=`Falha: ${e.message}`}}
document.addEventListener('DOMContentLoaded',()=>{buildHeader('targets');navMachines.onclick=e=>{e.preventDefault();location.hash='machines';showTab('machines')};navScans.onclick=e=>{e.preventDefault();location.hash='scans';showTab('scans')};targetsRefreshBtn.onclick=()=>Promise.all([loadTargets(),loadLast()]);targetsSearch.oninput=renderAssets;document.querySelectorAll('#machinesSection th[data-sort]').forEach(th=>th.onclick=()=>{const key=th.dataset.sort;if(assetSort.key===key)assetSort.direction=assetSort.direction==='asc'?'desc':'asc';else assetSort={key,direction:key.endsWith('_at')?'desc':'asc'};renderAssets()});newScanBtn.onclick=()=>scanFormCard.hidden=false;cancelScanBtn.onclick=()=>scanFormCard.hidden=true;scanSchedule.onchange=()=>{intervalLabel.hidden=scanSchedule.value!=='interval';scanEnabled.disabled=scanSchedule.value!=='interval'};saveScanBtn.onclick=saveScan;clearHistoryBtn.onclick=async()=>{if(confirm('Limpar todo o histórico de execuções?')){await json(await fetch('/api/targets/discovery-runs',{method:'DELETE'}));loadRuns()}};showTab(location.hash==='#scans'?'scans':'machines')});
