function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function dt(v){if(!v)return '—';try{return new Date(v).toLocaleString('pt-BR')}catch{return v}}
function sevLabel(v){return ({critical:'Critical',high:'High',medium:'Medium',low:'Low',info:'Info'})[v]||v||'Info'}
function evidenceText(e){if(!e)return '—';if(typeof e==='string'){try{e=JSON.parse(e)}catch{return e}}const bits=[];if(e.port)bits.push(`${e.port}/${e.protocol||'tcp'}`);if(e.service)bits.push(e.service);if(e.product)bits.push(e.product);if(e.process)bits.push(e.process);if(e.path)bits.push(e.path);if(e.detected_by)bits.push(`via ${e.detected_by}`);return bits.join(' · ')||'—'}
async function req(url,opt){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d}
async function load(){const qs=new URLSearchParams();if(statusFilter.value)qs.set('status',statusFilter.value);if(severityFilter.value)qs.set('severity',severityFilter.value);if(searchFilter.value.trim())qs.set('search',searchFilter.value.trim());const d=await req(`/api/exposures?${qs}`);const s=d.summary||{};openCount.textContent=s.status?.open||0;resolvedCount.textContent=s.status?.resolved||0;ignoredCount.textContent=s.status?.ignored||0;criticalCount.textContent=s.severity?.critical||0;highCount.textContent=s.severity?.high||0;mediumCount.textContent=s.severity?.medium||0;const rows=d.items||[];findingsTable.innerHTML=rows.length?rows.map(x=>`<tr><td><span class="asset-badge">${esc(sevLabel(x.severity))}</span></td><td><strong>${esc(x.title)}</strong><small style="display:block">${esc(x.category)}</small></td><td>${esc(x.display_name||x.hostname||x.ip_address)}<small style="display:block"><code>${esc(x.ip_address)}</code></small></td><td>${esc(evidenceText(x.evidence))}</td><td><span class="asset-status detected">${esc(x.status)}</span></td><td>${esc(dt(x.first_seen_at))}</td><td>${esc(dt(x.last_seen_at))}</td><td>${x.status==='ignored'?`<button class="btn secondary btn-sm" onclick="setFinding('${x.finding_uuid}','open')">Reabrir</button>`:`<button class="btn secondary btn-sm" onclick="setFinding('${x.finding_uuid}','ignored')">Ignorar</button>`}</td></tr>`).join(''):'<tr><td colspan="8">Nenhum finding para os filtros selecionados.</td></tr>'}
async function setFinding(id,status){let reason=null;if(status==='ignored')reason=prompt('Motivo para ignorar este finding (opcional):')||null;try{await req(`/api/exposures/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,reason})});load()}catch(e){alert(e.message)}}
async function rebuild(){rebuildBtn.disabled=true;rebuildBtn.textContent='Reavaliando...';try{await req('/api/exposures/rebuild',{method:'POST'});await load()}catch(e){alert(e.message)}finally{rebuildBtn.disabled=false;rebuildBtn.textContent='Reavaliar'}}
document.addEventListener('DOMContentLoaded',()=>{buildHeader('exposures');statusFilter.onchange=load;severityFilter.onchange=load;searchFilter.oninput=()=>{clearTimeout(window._expT);window._expT=setTimeout(load,250)};rebuildBtn.onclick=rebuild;load()});
