[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "magi-runner"
version = "2.14.0"
description = "Magi Runner v2"
requires-python = ">=3.10"
dependencies = [
  "requests>=2.32.0",
  "psutil>=5.9.8",
  "paramiko>=3.5.0",
  "pywin32>=306; platform_system == 'Windows'"
]

[tool.setuptools.packages.find]
include = ["magi_runner*"]
