param(
    [string]$ServiceName = "MagiRunnerV2",
    [string]$RunnerHome = (Resolve-Path ".").Path,
    [string]$ConfigPath = "settings.json"
)

$ErrorActionPreference = "Stop"

function Write-ServicePythonBootstrap {
    param([string]$RunnerHome, [string]$PythonExe)
    $sitePackages = & $PythonExe -c "import site; print(site.getsitepackages()[0])"
    $bootstrapPath = Join-Path $sitePackages "sitecustomize.py"
    $escapedRunnerHome = $RunnerHome.Replace('\\','\\\\').Replace('"','\"')
    $content = @"
# Auto-generated by Magi Runner installer.
import os
import sys
_runner_home = os.environ.get("MAGI_RUNNER_HOME") or r"$escapedRunnerHome"
if _runner_home and _runner_home not in sys.path:
    sys.path.insert(0, _runner_home)
"@
    Set-Content -Path $bootstrapPath -Value $content -Encoding UTF8
}

function Set-ServiceEnvironment {
    param([string]$ServiceName, [string]$RunnerHome, [string]$ConfigPath)
    $svcRegPath = "HKLM:\SYSTEM\CurrentControlSet\Services\$ServiceName"
    if (Test-Path $svcRegPath) {
        $envValues = @(
            "MAGI_RUNNER_HOME=$RunnerHome",
            "MAGI_RUNNER_CONFIG=$(Join-Path $RunnerHome $ConfigPath)",
            "PYTHONPATH=$RunnerHome"
        )
        New-ItemProperty -Path $svcRegPath -Name Environment -PropertyType MultiString -Value $envValues -Force | Out-Null
    }
}

$python = Join-Path $RunnerHome ".venv\Scripts\python.exe"
if (!(Test-Path $python)) {
    Write-Host "Virtualenv not found. Running scripts\install.ps1 first..."
    & (Join-Path $RunnerHome "scripts\install.ps1")
}

$env:MAGI_RUNNER_HOME = $RunnerHome
$env:MAGI_RUNNER_CONFIG = Join-Path $RunnerHome $ConfigPath

& $python -m pip install pywin32
Write-ServicePythonBootstrap -RunnerHome $RunnerHome -PythonExe $python
& $python .\scripts\service_control.py --startup auto install

# Persist service environment variables at machine level for service startup.
[Environment]::SetEnvironmentVariable("MAGI_RUNNER_HOME", $RunnerHome, "Machine")
[Environment]::SetEnvironmentVariable("MAGI_RUNNER_CONFIG", (Join-Path $RunnerHome $ConfigPath), "Machine")

Set-ServiceEnvironment -ServiceName $ServiceName -RunnerHome $RunnerHome -ConfigPath $ConfigPath
sc.exe failure $ServiceName reset= 86400 actions= restart/60000/restart/60000/restart/300000 | Out-Null
Write-Host "Service installed: $ServiceName"
Write-Host "Start with: scripts\start_service.ps1"
